oriansj/M2libc

amd64/amd64_defs.M1
amd64/uefi/PE32-amd64.hex2
amd64/uefi/bootstrap.c
amd64/uefi/libc-core.M1

Built `M2.efi` using this and used it to build `M1-0.efi`.

Add amd64 UEFI support.

---

amd64/uefi/bootstrap.c
amd64/uefi/fcntl.c
amd64/uefi/uefi.c
amd64/uefi/unistd.c

Tested with
```
#include <stdio.h>
int main(int argc, char** argv)
{
FILE f = fopen("amd64/cc_amd64.M1", "r");
if(f)
{
return fgetc(f);
}
return 1;
}
```
No support for reading from stdin yet. Seeking is also not implemented.

Imlement UEFI file opening, closing and reading.

---

amd64/uefi/libc-full.M1
amd64/uefi/uefi.c
string.h

tested with kaem, it can now see env variables set by UEFI shell and can print e.g.
`echo ${var}`
if we set `var` in UEFI shell.

Populate envp array on startup of UEFI application.

---

aarch64/libc-full.M1
amd64/amd64_defs.M1
amd64/libc-full.M1
armv7l/libc-full.M1
knight/libc-full.M1
riscv32/libc-full.M1
riscv64/libc-full.M1
stdlib.c
stdlib.h
x86/libc-full.M1

knight-posix and armv7l do not support it yet.
Tested by adding `puts(getenv("LEX"));` to sha256sum

Implement getenv for x86, amd64, aarch64, riscv32 and riscv64.

---

string.c

As a test case,
previously strncmp("a", "ab", 2) == 0 (which is clearly incorrect)

Make strncmp correct when count > len(lhs)

---

amd64/amd64_defs.M1
amd64/uefi/bootstrap.c
amd64/uefi/libc-core.M1
amd64/uefi/libc-full.M1
uefi/uefi.c

* Stack should be aligned to 16 bytes
* UEFI shadow stack space should be 32 bytes even for functions with less than 4 arguments
* Non-volatile registers must be restored before the program exist

Fix UEFI calling convention.

---

uefi/unistd.c

cp from mescc-tools-extra relies on this.

uefi: chdir: return -1 if path does not exist.

---

stdio.c

Typically fgets returns NULL when EOF occus and no characters have been read. Align this behaviour with POSIX impls.

Fix fgets behaviour when EOF reached

---

uefi/uefi.c

It is expected by the UEFI specification that when a variable is retrieved with NULL data, the data length is 0. Previous behaviour in M2libc did not conform.
It appears some UEFI implementations depend on this and some do not (notably, EDK2 does not, but many bare metal platforms do).

Make variable getting to-spec

---

aarch64/linux/unistd.c
amd64/linux/unistd.c
armv7l/linux/unistd.c
knight/linux/unistd.c
knight/native/unistd.c
riscv32/linux/unistd.c
riscv64/linux/unistd.c
uefi/unistd.c
unistd.h
x86/linux/unistd.c

This change removes the "const" specifier for the "symlink()" syscall wrappers, due to an incompatibility with M2-Planet.

Update symlink() syscall wrappers

---

aarch64/linux/unistd.c

This change fixes an error when merging in #17 as part of #65.

Fix mis-merged error in unlink wrapper on Linux/aarch64

---

stdbool.h

`bool` could also be an `int` but all the major compilers have sizeof(bool) == 1.
The standard (C17) says in 6.2.5.2:
```text
An object declared as type _Bool is large enough to store the values 0 and 1
```
`_Bool` could also have been defined, although I don't think that's standards conforming it has to be a compiler handled type.

Add stdbool.h header

---

stdlib.c

This will been fixed in M2-Planet in https://github.com/oriansj/M2-Planet/issues/66 although I'm not entirely sure which order it should be fixed in or if this needs to be ifdeffed in case other compilers without correct pointer arithmetic also use `M2libc`.

Remove incorrect pointer arithmetic from setenv/getenv

---

bootstrappable.c

The literal `1` is an `int` which can't be bit shifted `31` times. This triggers UBSAN on GCC.
@oriansj @stikonas

Removed undefined behavior in int2str

---

amd64/amd64_defs.M1

This is useful for better codegen in M2-Planet at https://github.com/oriansj/M2-Planet/blob/664cf10452068e6280fae78990f082bdbfe20dd1/cc_core.c#L2562.
Verify with `echo "main: mov     rbx, rax" > main.s && nasm -f elf64 main.s && objdump -d main.o`:
```text
main.o:     file format elf64-x86-64
Disassembly of section .text:
0000000000000000 <main>:
0:   48 89 c3                mov    %rax,%rbx
```

Add amd64 mov_rbx,rax instruction

---

amd64/amd64_defs.M1
x86/x86_defs.M1

This is the recommended way of zeroing out a register, even for amd64 since zeroing the lower 32 bits automatically also zeros out the upper 32 bits.
I didn't bother with the stack pointer and base pointer registers since we probably don't need to zero those.
@stikonas @oriansj 
```asm
main:
xor eax, eax
xor ebx, ebx
xor ecx, ecx
xor edx, edx
xor edi, edi
xor esi, esi
```
```sh
nasm -f elf32 main.s && objdump -d main.o
```
leads to
```text
main.o:     file format elf32-i386
Disassembly of section .text:
00000000 <main>:
0:   31 c0                   xor    %eax,%eax
2:   31 db                   xor    %ebx,%ebx
4:   31 c9                   xor    %ecx,%ecx
6:   31 d2                   xor    %edx,%edx
8:   31 ff                   xor    %edi,%edi
a:   31 f6                   xor …
```

Add xor_reg,reg for zeroing out registers for amd64/x86

---

amd64/amd64_defs.M1
x86/x86_defs.M1

@stikonas @oriansj 
These already exist for the others but were emulated on x86/amd64 with a mov afterwards.
```bash
printf "_start: sub rax, rbx\nsub eax, ebx" > main.s && nasm -f elf64 main.s && objdump -M intel -d main.o
main.o:     file format elf64-x86-64
Disassembly of section .text:
0000000000000000 <_start>:
0:	48 29 d8             	sub    rax,rbx
3:	29 d8                	sub    eax,ebx
```

Add sub_rax,rbx for x86/amd64

---

stdarg.h
stdio.c
stdio.h

Is not blocked by or blocking https://github.com/oriansj/M2-Planet/pull/116.
Adds defines for the intrinsics added by the previous PR.
Also adds printf family with support only for `%s` (strings).
@stikonas

Add `stdarg.h` and initial printf and friends

---

stdio.c

This fixes incorrect return values from the printf family as well as refactoring stream based printfs to use the same implementation as the buffer based. This will ease the maintenance burden.
When stack arrays correctly decay to pointers we could use stack based buffers instead of globals, but that will require fixes in M2-Planet.

Fix issues with printf and refactor into single implementation

---

sys/stat.h
unistd.h

With functional include support in M2-Planet including `sys/stat.h` or `unistd.h` fails for Knight because of this.

Add knight defines to unistd.h/stat.h

---

x86/linux/unistd.c

The ESI register needs to be saved and restored because it stores/restores the stack pointer prologue and epilogue of functions

Fix x86 chroot

---

uefi/unistd.c

@stikonas @oriansj 
[oriansj/M2-Planet@`413c69f` (#120)](https://github.com/oriansj/M2-Planet/pull/120/commits/413c69f4a58ff3e294572549875195df9ccfb5a8) introduced a regression for UEFI where output was not working correctly.
This is because UEFI uses UTF-16 for strings and in the commit we allocated stack space by pushes which zeros the upper bytes while store_value did not. The UTF-16 string required 3 byte of zeroes after the initial character value. Because we only wrote to the lower part of the register the top parts were effectively uninitialized.

Fix UEFI writes acting strange after M2-Planet changes

---

amd64/linux/bootstrap.c

This also allows us to get the better performance in fputs which is used extensively in M2-Planet.

amd64: Refactor write out of fwrite and use in fputs

---

amd64/linux/bootstrap.c

This removes the duplicated assembly as requested in https://github.com/oriansj/M2libc/pull/95.
Since we don't have the address-of operator it has to be done either this way or by something like
```c
char* c;
asm("lea rax,[rsp+DWORD] %0"
"lea rbx, [rsp+DWORD] %24"
"mov_[rbx],rax");
write(f, c, 1);
```
Which is IMO way more brittle. With modern CPU branch prediction I don't expect the NULL check and allocation to have any significance.
I plan on doing a proper `read` as well reusing this buffer for `fgetc`.

amd64: Implement fputc with write

---

amd64/linux/bootstrap.c

For my assembler on WSL this impressively reduces a single test execution time from ~50 seconds to < 3 seconds using a simple buffer rather than repeatedly calling `fgetc` like we do in M2-Planet.
Perhaps this might also be worthwhile for very slow systems like RISC-V? I'm not sure if the syscall overhead dominates as much or if it's just generally slow.

amd64: Add optimized read function

---

aarch64/linux/bootstrap.c
armv7l/linux/bootstrap.c
riscv32/linux/bootstrap.c
riscv64/linux/bootstrap.c

Somehow I missed the aarch64 fread in #94.
Optimized `fread`/`fwrite`s like in https://github.com/oriansj/M2libc/pull/99.

Add optimized read/write for riscv32/riscv64/aarch64
